name: Versioning and Release with Release Notes and Slack Notification

on:
  push:
    branches:
      - main

jobs:
  version-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v5.0.2
        with:
          branch: main
          tag_prefix: "release-"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"
      - name: Create tag
        run: |
          git tag release-${{ steps.versioning.outputs.version }}
          git push --tags
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: ".github/workflows/changelogConfig.json"
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ steps.versioning.outputs.version }}
          release_name: "Release ${{ steps.versioning.outputs.version }}"
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Post to Slack
        run: |
            export SLACK_TEXT="Release ${{ steps.versioning.outputs.version }} \n\nChangelog: ${{ steps.build_changelog.outputs.changelog }}"
            curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"${SLACK_TEXT}\"}" \
            https://hooks.slack.com/services/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