name: CI

on:
    pull_request:
      types:
        - opened


concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    create-release-pr:
        name: Release
        timeout-minutes: 15
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        if: github.event.pull_request.base.ref == 'main'
        steps:
            - name: Check out code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2
                  token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  version: latest
            - name: Install dependencies
              run: npm install
            - name: Create Release Pull Request
              if: github.ref == 'refs/heads/main'
              uses: changesets/action@v1
              with:
                title: "Release"
                commit: "chore: release"
              env:
                  GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
