name: CI

on:
    push:
        branches: ["main"]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    ci:
        name: Release
        timeout-minutes: 15
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Check out code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2
                  token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  version: latest
            - name: Install dependencies
              run: npm install
#            - name: Release snapshot
#              run: |
#                npx changeset version
#                npx changeset tag
#              env:
#                GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
            - name: Create Release Pull Request
              if: github.ref == 'refs/heads/main'
              uses: changesets/action@v1
              with:
                translation: npm run translation
              env:
                  GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
