name: create-release-pr

on:
    push:
        branches: ["main"]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    create-release-pr:
        name: create-release-pr
        timeout-minutes: 15
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        if: github.event.pull_request.title != 'Release'
        steps:
            - name: Check out code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2
                  token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  version: latest
            - name: Install dependencies
              run: npm install
            - name: Changesets
              id: changesets
              uses: changesets/action@v1
              env:
                GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
              with:
                publish: npx changeset tag
                commit: "chore: release"
                title: "Release"
