name: release

on:
  push:
    branches: [ "main" ]
#  pull_request:
#      types:
#        - closed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
        name: Release
        timeout-minutes: 15
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        #if: contains(github.event.pull_request.head.ref, 'changeset-release')
        steps:
            - name: echo pull request info
              run: |
                echo ${{ github.event.pull_request.title }}
                echo ${{ github.event.pull_request.head.ref }}
            - name: Check out code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2
                  token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  version: latest
            - name: Install dependencies
              run: npm install
            - name: Release
              run: | 
                npx changeset tag
                npx changeset publish
