name: release

on:
  push:
    branches: [ "main" ]
#  pull_request:
#      types:
#        - closed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
        name: Release
        timeout-minutes: 15
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        #if: contains(github.event.pull_request.head.ref, 'changeset-release')
        steps:
            - name: echo pull request info
              run: |
                echo ${{ github.event.pull_request.title }}
                echo ${{ github.event.pull_request.head.ref }}
            - name: Check out code
              uses: actions/checkout@v3
#              with:
#                  fetch-depth: 2
#                  token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  version: latest
            - name: Install dependencies
              run: npm install
            - name: Create tag
              run: |
                git tag --list
                npx changeset tag
                git tag --list
            - name: GIT commit and push all changed files
              env:
                CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
                CI_COMMIT_AUTHOR: Continuous Integration
              run: |
                git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
                git config --global user.email "username@users.noreply.github.com"
                git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
                git push --follow-tags
